name: Generate Plot and Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Start Elasticsearch
        run: |
          docker run -d \
            --name elasticsearch \
            -p 9200:9200 \
            -e "discovery.type=single-node" \
            -e "xpack.security.enabled=false" \
            docker.elastic.co/elasticsearch/elasticsearch:8.10.2

          # Esperar hasta que Elasticsearch esté listo
          echo "⏳ Waiting for Elasticsearch to be ready..."
          sleep 30

          # Verificar que Elasticsearch está levantado
          curl -X GET "http://localhost:9200/"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install elasticsearch pandas matplotlib

      - name: Load data into Elasticsearch
        run: |
          python load_data.py

      - name: Generate Plot
        run: |
          python plot_data.py

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: .
